 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
       - checkout
       - run: msbuild LangLib/LangLib.csproj /t:restore
       - run: msbuild LangLib/LangLib.csproj /p:Configuration=Release
       - run:
          name: Push to NuGet
          command: |
            msbuild LangLib/LangLib.csproj /p:Configuration=Release /t:pack
